// <auto-generated />
using Dami.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace dami.data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.24");

            modelBuilder.Entity("Dami.Data.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CUSTOMERS", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "",
                            FullName = "customer1"
                        },
                        new
                        {
                            Id = 2,
                            Email = "",
                            FullName = "custmer2"
                        },
                        new
                        {
                            Id = 3,
                            Email = "",
                            FullName = "customer3"
                        },
                        new
                        {
                            Id = 4,
                            Email = "",
                            FullName = "customer4"
                        },
                        new
                        {
                            Id = 5,
                            Email = "",
                            FullName = "customer5"
                        });
                });

            modelBuilder.Entity("Dami.Data.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PRODUCTS", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Product1",
                            Price = 0m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Product2",
                            Price = 0m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Product3",
                            Price = 0m
                        },
                        new
                        {
                            Id = 4,
                            Name = "Product4",
                            Price = 0m
                        },
                        new
                        {
                            Id = 5,
                            Name = "Product5",
                            Price = 0m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
